name: Build Standalone App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8]

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v4

    # Set up Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    # Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    # Build standalone executable
    - name: Build Application
      run: |
        pyinstaller --onefile pathology-downloader.py
      shell: bash

    # Upload artifacts
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: pathology-downloader-${{ matrix.os }}
        path: dist/pathology-downloader*
